# Generated by Django 5.2.4 on 2025-08-01 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance_app.framework')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('uploaded_file', models.FileField(upload_to='policies/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('change_summary', models.JSONField(default=dict)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance_app.policy')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyDiff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.CharField(max_length=50)),
                ('diff_text', models.TextField()),
                ('change_details', models.JSONField(default=dict)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diffs', to='compliance_app.policyversion')),
            ],
        ),
        migrations.CreateModel(
            name='PolicySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('archived', models.BooleanField(default=False)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='compliance_app.policyversion')),
            ],
            options={
                'unique_together': {('version', 'section_number')},
            },
        ),
    ]
